dist: trusty

os:
- linux

sudo: required

language: bash

services:
  - docker
  
before_install:
  - chmod +x build.sh
  - chmod +x test.sh
  
install: ./build.sh

script: ./test.sh

notifications:
  webhooks:
    on_success: change
    on_failure: always
    on_start: never
  email:
    - gjero@krsteski.de
    
